//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласен с .
        /// </summary>
        internal static string AgreeWithMessage {
            get {
                return ResourceManager.GetString("AgreeWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все гости.
        /// </summary>
        internal static string AllGuests {
            get {
                return ResourceManager.GetString("AllGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список гостей.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гости, посетившие мероприятие.
        /// </summary>
        internal static string ArrivedGuests {
            get {
                return ResourceManager.GetString("ArrivedGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закончить мероприятие.
        /// </summary>
        internal static string EndEvent {
            get {
                return ResourceManager.GetString("EndEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список гостей.
        /// </summary>
        internal static string GuestList {
            get {
                return ResourceManager.GetString("GuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация гостя на мероприятие.
        /// </summary>
        internal static string GuestRegistration {
            get {
                return ResourceManager.GetString("GuestRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО.
        /// </summary>
        internal static string GuestRegistrationViewModel_FIO {
            get {
                return ResourceManager.GetString("GuestRegistrationViewModel_FIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактный телефон.
        /// </summary>
        internal static string GuestRegistrationViewModel_Phone {
            get {
                return ResourceManager.GetString("GuestRegistrationViewModel_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам необходимо согласиться с условиями!.
        /// </summary>
        internal static string IsGuestNotAggree {
            get {
                return ResourceManager.GetString("IsGuestNotAggree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гости, не посетившие мероприятие.
        /// </summary>
        internal static string NotArrivedGuests {
            get {
                return ResourceManager.GetString("NotArrivedGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для участия в мероприятии, вам необходимо заполнить, ниже перечисленные поля.
        ///    
        ///
        ///Обращаем ваше внимание, на точто все поля являются обязательными..
        /// </summary>
        internal static string RegistrationInfoMessage {
            get {
                return ResourceManager.GetString("RegistrationInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск гостей по ФИО, email, телефон.
        /// </summary>
        internal static string SearchGuests {
            get {
                return ResourceManager.GetString("SearchGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На указанный вами адрес электронной почты придет приглашение для участия в мероприятии..
        /// </summary>
        internal static string SuccesRegistrationMessage {
            get {
                return ResourceManager.GetString("SuccesRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to условиями.
        /// </summary>
        internal static string TermsMessage {
            get {
                return ResourceManager.GetString("TermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за регистрацию!.
        /// </summary>
        internal static string ThankyouForRegistrationMessage {
            get {
                return ResourceManager.GetString("ThankyouForRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо!.
        /// </summary>
        internal static string ThankyouMessage {
            get {
                return ResourceManager.GetString("ThankyouMessage", resourceCulture);
            }
        }
    }
}
